version: '3.7'

services:
  django_gunicorn:
    volumes:
      - ./Upload/static:/static
      - /tmp/file:/app/media
    env_file:
      - .env
    build:
      context: .
    ports:
      - "80:8000"
    restart: always
  nginx:
    build: ./nginx
    volumes:
      - ./Upload/static:/static
      - /tmp/file:/app/media
    ports:
      - "8000:80"
    depends_on:
      - django_gunicorn

volumes:
  static:
  media:

